/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/daily-style-questions': RouteRecordInfo<'/posts/daily-style-questions', '/posts/daily-style-questions', Record<never, never>, Record<never, never>>,
    '/posts/destructuring-with-object-or-array': RouteRecordInfo<'/posts/destructuring-with-object-or-array', '/posts/destructuring-with-object-or-array', Record<never, never>, Record<never, never>>,
    '/posts/leetcode': RouteRecordInfo<'/posts/leetcode', '/posts/leetcode', Record<never, never>, Record<never, never>>,
    '/posts/node-modularity': RouteRecordInfo<'/posts/node-modularity', '/posts/node-modularity', Record<never, never>, Record<never, never>>,
    '/posts/oauth-2.0': RouteRecordInfo<'/posts/oauth-2.0', '/posts/oauth-2/0', Record<never, never>, Record<never, never>>,
    '/posts/simple-reactive': RouteRecordInfo<'/posts/simple-reactive', '/posts/simple-reactive', Record<never, never>, Record<never, never>>,
    '/posts/structure': RouteRecordInfo<'/posts/structure', '/posts/structure', Record<never, never>, Record<never, never>>,
    '/posts/webpack-compiler-hook': RouteRecordInfo<'/posts/webpack-compiler-hook', '/posts/webpack-compiler-hook', Record<never, never>, Record<never, never>>,
  }
}
